# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
  -
    hooks:
      -
        id: check-yaml
      -
        id: check-json
    repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v2.0.0
  -
    hooks:
      -
        id: autopep8
    repo: "https://github.com/pre-commit/mirrors-autopep8"
    rev: "v1.4.4"
  -
    hooks:
      -
        id: flake8
    repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v1.2.3
